version: '3'

services:
  portal-backend:
    image: portal-backend
    hostname: portal-backend
    container_name: portal-backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    restart: unless-stopped
