version: '3'

services:
  portal-api:
    image: portal-api
    hostname: portal-api
    container_name: portal-api
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    restart: unless-stopped
