version: '3'

services:
  portal:
    image: nginx:latest
    hostname: portal
    container_name: portal
    ports:
      - ${PORT:-80}:80
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
