= API

This is the documentation for the API (`/backend`).
The API base url is located at `/api`.
Authentication is done with with either `username:password` or `token:x`.


=== Routes

==== Healthcheck

|==============
|URL          |*/api/health*
|Description
a|Return API health.
|Method       |GET
|Requires Auth|False
|curl         |`curl -i -X GET http://127.0.0.1:5000/api/health`
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 21
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 10:25:37 GMT

{
  "status": "ok"
}
-----------------
|==============

==== Register user

|==============
|URL          |*/api/users*
|Description
a|Register a new user.
 +
The body must contain a JSON object that defines `username` and `password` fields.
 +
On success a status code 201 is returned. The body of the response contains a JSON object with the newly added user.
 +
A `Location` header contains the URI of the new user.
 +
On failure status code 400 (bad request) is returned.
 +
Notes:

* The password is hashed before it is stored in the database. Once hashed, the original password is discarded.
* In a production deployment secure HTTP must be used to protect the password in transit.
|Method       |POST
|Requires Auth|False
|curl         |`curl -i -X POST -H "Content-Type: application/json" -d '{"username":"uname","password":"pword"}' http://127.0.0.1:5000/api/users`
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 201 CREATED
Content-Type: application/json
Location: http://127.0.0.1:5000/api/users/1
Content-Length: 26
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 09:45:28 GMT

{
  "username": "uname"
}
-----------------
|==============

==== User id

|==============
|URL          |*/api/users/`<int:id>`*
|Description
a|Return a user.
 +
On success a status code 200 is returned. The body of the response contains a JSON object with the requested user.
 +
On failure status code 400 (bad request) is returned.
|Method       |GET
|Requires Auth|False
|curl         |`curl -i -X GET http://127.0.0.1:5000/api/users/1`
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 26
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 10:07:54 GMT

{
  "username": "uname"
}
-----------------
|==============

==== User token

|==============
|URL          |*/api/token*
|Description
a|Return an authentication token.
 +
This request must be authenticated using a HTTP Basic Authentication header.
 +
On success a JSON object is returned with a field `token` set to the authentication token for the user and a field `duration` set to the (approximate) number of seconds the token is valid.
 +
On failure status code 401 (unauthorized) is returned.
|Method       |GET
|Requires Auth|True
|curl         |`curl -u uname:pword -i -X GET http://127.0.0.1:5000/api/token`
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 160
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 10:13:29 GMT

{
  "duration": 600,
  "token": "eyJhbGciOiJIUzI1NiIsImlhdCI6MTU4MTU4ODgwOSwiZXhwIjoxNTgxNTg5NDA5fQ.eyJpZCI6MX0.hutgxnT_b292IVmPv4dLRfM9YEQhd7bZBVZJKyFZ77E"
}
-----------------
|==============

==== Resource

|==============
|URL          |*/api/resource*
|Description
a|Return a protected resource.
This request must be authenticated using a HTTP Basic Authentication header. Instead of username and password, the client can provide a valid authentication token in the username field. If using an authentication token the password field is not used and can be set to any value.
On success a JSON object with data for the authenticated user is returned.
On failure status code 401 (unauthorized) is returned.
|Method       |GET
|Requires Auth|True
|curl         |`curl -u uname:pword -i -X GET http://127.0.0.1:5000/api/resource`
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 29
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 10:21:22 GMT

{
  "data": "Hello, uname"
}
-----------------
|==============


=== Generic responses

==== Unauthorized

|==============
|Routes       |`Requires Auth`
|Description
a|Unauthorized request.
|Response Body
a|
[source,sh]
-----------------
HTTP/1.0 401 UNAUTHORIZED
Content-Type: text/html; charset=utf-8
Content-Length: 19
WWW-Authenticate: Basic realm="Authentication Required"
Server: Werkzeug/0.12.2 Python/3.8.1
Date: Thu, 13 Feb 2020 10:16:42 GMT

Unauthorized Access
-----------------
|==============
