name: wiki

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish to GitHub Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
      with:
        path: docs
